version: '3'
services: 
  app:
    container_name: budget-calculator
    # restart: always
    build: 
        context: ./my-app
        dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    depends_on:  
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '4000:4000'    