version: '3'
services: 
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - '3000:3000'
    networks: 
      - mern-app     
    links: 
      - backend
    depends_on: 
      - backend  
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - '4000:4000' 
    depends_on: 
      - mongoDB
    networks: 
      - mern-app     
  mongoDB:
    container_name: mongo
    image: mongo:4.2
    ports: 
      - '27017:27017'  
    networks: 
      - mern-app   
    volumes: 
      - mongo-data:/data/db   

networks: 
    mern-app:
      driver: bridge 
volumes:
    mongo-data:
      driver: local
