version: '3'
services: 
  app:
    container_name: budget-calculator
    restart: always
    build: .
    ports: 
      - '3000:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '4000:4000'    